### ISSUE TITLE
Deploy to Azure

### ISSUE THREAD

**Issue by rwilson504** [rajyraman/PowerApps-Managed-Identity-Demo-Functions#1]
Hey @rajyraman thank you for posting this.  Do you have any documentation on what you would do after using the Deploy to Azure functionality to just get this up and running and may just have a simple Function that would return a record?

After I deployed I couldn't really do anything with it because of the WEBSITE_RUN_FROM_PACKAGE and there were not actual functions within the azure app.

Thanks!

Rick

**Comment by rajyraman** [comment]
@rwilson504 - The deploy to azure button only creates the resources on Azure. The Function App DLL has to be still deployed using Function CLI. You can refer run.ps1 in the deploy folder, from line 9 onwards.

**Comment by rajyraman** [comment]
@rwilson504 - Added more documentation to make it clear.

**Comment by rwilson504** [comment]
Thank you so much for posting this and updating the docs, I was able to deploy using these instructions.
